<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Recipient, , s Email)_giftcard_7eddd1</name>
   <tag></tag>
   <elementGuidId>8c372983-a1a7-428b-8b6e-5c8a7d084163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#giftcard_43_RecipientEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='giftcard_43_RecipientEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f79cb7b-b51f-4bcc-a008-56a63fb704d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>recipient-email</value>
      <webElementGuid>98695aca-dfef-4bab-b516-0f325ac258f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>3f04526f-c573-4451-8d2f-871373c5bcaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>giftcard_43_RecipientEmail</value>
      <webElementGuid>d49f2ca6-9c27-4168-acd2-cf9fe65a4e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>giftcard_43.RecipientEmail</value>
      <webElementGuid>6523de1a-fcb4-47d1-8178-7fd79af4bab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;giftcard_43_RecipientEmail&quot;)</value>
      <webElementGuid>fc4b4bc2-7338-4c8f-9573-cc68a0001892</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='giftcard_43_RecipientEmail']</value>
      <webElementGuid>748fd9be-7bf2-46c9-9d7a-f3b33de12d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div[2]/div/div[2]/div[5]/div[2]/input</value>
      <webElementGuid>ac95ecd2-9ada-4ab3-9d4d-438acadda9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>34f5a127-4cc6-4ade-a5bd-4ba5bbc36eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'giftcard_43_RecipientEmail' and @name = 'giftcard_43.RecipientEmail']</value>
      <webElementGuid>f2c66c69-7388-4c34-b6cc-16e4b04a06ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
