<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your Email_giftcard_43.SenderEmail</name>
   <tag></tag>
   <elementGuidId>301a82f4-a267-4d26-b41f-f14ba6297d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#giftcard_43_SenderEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='giftcard_43_SenderEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b03891bd-c6a0-459a-939e-24dc49250041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sender-email</value>
      <webElementGuid>c805bef2-481c-47a0-b8cc-42b2fdbb1237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>a1c67e4a-79d0-4baa-8c4e-ea54095d4f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>giftcard_43_SenderEmail</value>
      <webElementGuid>b19925a2-b726-4419-9a7c-70cbe3542a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>giftcard_43.SenderEmail</value>
      <webElementGuid>61096e3b-35e6-48a2-ad4e-105b4b793271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;giftcard_43_SenderEmail&quot;)</value>
      <webElementGuid>7d84f777-5083-49d0-b6f4-5febbbaaa059</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='giftcard_43_SenderEmail']</value>
      <webElementGuid>8484acce-4360-4873-b8e6-3032d20e83e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div[2]/div/div[2]/div[5]/div[4]/input</value>
      <webElementGuid>22800ff8-0fe7-4713-aabc-960fc75f79ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>b09a6184-5836-41f6-bb25-5c151a293d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'giftcard_43_SenderEmail' and @name = 'giftcard_43.SenderEmail']</value>
      <webElementGuid>03aa6de6-be88-4d67-adff-86c1d630ff59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
