<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Message_giftcard_43.Message</name>
   <tag></tag>
   <elementGuidId>2ed9ec6f-7366-48d2-b491-ff6bd2fa5641</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#giftcard_43_Message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='giftcard_43_Message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2a9a82c3-919e-40b3-96d8-987d80238310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>e3782a34-d466-4b6d-ac74-7459e7f9dfa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>giftcard_43_Message</value>
      <webElementGuid>e1c1cc2e-58f9-4e7e-b314-83ada577d45f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>giftcard_43.Message</value>
      <webElementGuid>38f1bf23-8d6e-4630-977e-6a45221bfd2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;giftcard_43_Message&quot;)</value>
      <webElementGuid>2abee627-db62-40be-8b6a-727d56ca7515</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='giftcard_43_Message']</value>
      <webElementGuid>d0aed012-39e6-4ab0-96b9-173d3eddd49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div[2]/div/div[2]/div[5]/div[5]/textarea</value>
      <webElementGuid>76d65fe9-bd6d-4de5-9b8c-141c019491d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>59a11438-2442-4fff-a9f4-061856663468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'giftcard_43_Message' and @name = 'giftcard_43.Message']</value>
      <webElementGuid>b488babb-605c-4f9f-9116-74109337e5c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
