<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Address</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>false</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5a47bb79-4f25-4af0-80dd-562e7b14d953</testSuiteGuid>
   <testCaseLink>
      <guid>6d875eaf-0e5a-4485-8f0e-08ebfd4f1712</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Address/TC_Add Address</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e48f7a8a-590c-4dad-bfd9-842fe5bdbbbd</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DF_Address</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>e48f7a8a-590c-4dad-bfd9-842fe5bdbbbd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>id</value>
         <variableId>6cac3faa-7b39-4468-8fa7-fe1f4bdca2ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e48f7a8a-590c-4dad-bfd9-842fe5bdbbbd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>firstname</value>
         <variableId>6f31d75e-d459-426b-b1d6-80c930b3a11b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e48f7a8a-590c-4dad-bfd9-842fe5bdbbbd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>lastname</value>
         <variableId>8ba0c90b-9d1b-4977-8559-5cfd77a02d33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e48f7a8a-590c-4dad-bfd9-842fe5bdbbbd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>fe7821bc-6c58-4158-8493-5539c19ee9f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e48f7a8a-590c-4dad-bfd9-842fe5bdbbbd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>country</value>
         <variableId>2fe08ed8-785d-4830-b1bb-bdd6193a64c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e48f7a8a-590c-4dad-bfd9-842fe5bdbbbd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>city</value>
         <variableId>a24fdd19-fcc3-444a-a666-366a5ca2d24b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e48f7a8a-590c-4dad-bfd9-842fe5bdbbbd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>address</value>
         <variableId>ff34b426-8fcb-4253-ada6-95f5f5ed0556</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e48f7a8a-590c-4dad-bfd9-842fe5bdbbbd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>zipcode</value>
         <variableId>9ff37f4f-1dda-4f21-abf3-b56a0aa5e9a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e48f7a8a-590c-4dad-bfd9-842fe5bdbbbd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>phone</value>
         <variableId>919a48fe-ef2f-47d6-a36f-7d8b74a9fa93</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ed92591-bda2-42ef-930f-116cfb72e7cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Address/TC_Edit Address</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18c0eb89-7b31-4196-b41f-310775bcef7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d98322e-b577-45c4-805e-ce8402d17f36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09a618fb-29f6-42e1-8650-333c07a4ebec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaca3014-b822-4b66-8545-d80700848e91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>200f7c32-5b24-41c1-8e10-ed9b19c1d418</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7018bc7f-ea60-4de5-8022-085e2a285847</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1faf7190-08cf-43d9-b281-d5917dd6cb21</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e121bc9f-744e-43e7-8f89-b3d037562660</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c9a4ec1e-9f9e-4347-99ea-eeefc26c5ac2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Address/TC_Delete Address</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
