<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Cart</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>false</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>1b6bc5ee-acfd-4419-ae0b-cf88fbb7b40d</testSuiteGuid>
   <testCaseLink>
      <guid>21486d26-465f-47dd-a37e-155023df89a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC_Add Product/TC_Add Product_030405_CheckQuantity</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>51a70588-9bbc-49f7-82a6-3e678b5f150e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC_Add Product/TC_Add Product_01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5795138-b9ec-4100-9c00-dcceda75fdb4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>efa28382-f015-473f-a548-228386995405</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC_Add Product/TC_Add Product_02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>cb7d1f6a-1015-455e-951d-f5d03d12cd4f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC_Update Cart</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>93d9da19-4700-426d-af19-e1f4e9a9a22e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DF_CartUpdate</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>93d9da19-4700-426d-af19-e1f4e9a9a22e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>id</value>
         <variableId>99443bbd-1923-4038-a627-34e3266e7e88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>93d9da19-4700-426d-af19-e1f4e9a9a22e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>qty</value>
         <variableId>2cf05cd7-49a9-4aef-98f4-afec406d98b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>93d9da19-4700-426d-af19-e1f4e9a9a22e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>description</value>
         <variableId>5b97e16c-4885-44ba-81d0-89c9724ece47</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d81eaf88-44ad-43c3-a922-911c6d404aa5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC_Delete Product</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
