<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Cart</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>false</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>1b6bc5ee-acfd-4419-ae0b-cf88fbb7b40d</testSuiteGuid>
   <testCaseLink>
      <guid>6a117a0b-36df-4199-83be-36a62cb781d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Cart/TC_Add Product/TC_Add Product_01_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5795138-b9ec-4100-9c00-dcceda75fdb4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b2afecd-d274-42a2-946c-1f808fd3f4a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Cart/TC_Add Product/TC_Add Product_02_Fail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>2977e54d-0e9e-4300-ad4a-e2369945cb75</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/TC_Update Cart</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>fbb2d934-74aa-4d82-9320-17da5a9ca643</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DF_CartUpdate</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>fbb2d934-74aa-4d82-9320-17da5a9ca643</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>id</value>
         <variableId>99443bbd-1923-4038-a627-34e3266e7e88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fbb2d934-74aa-4d82-9320-17da5a9ca643</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>qty</value>
         <variableId>2cf05cd7-49a9-4aef-98f4-afec406d98b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fbb2d934-74aa-4d82-9320-17da5a9ca643</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>description</value>
         <variableId>5b97e16c-4885-44ba-81d0-89c9724ece47</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dc0f43de-f0eb-4658-8754-deba15f191cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Cart/TC_Delete Product</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
