<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>false</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a24dcca7-600c-4165-b5fa-1e3e977ebe0d</testSuiteGuid>
   <testCaseLink>
      <guid>4d9c15ce-0d5e-4f4c-9ea7-5b9e369eab29</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>27889d92-ed07-41b7-9939-36f9cc1f8bf5</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DF_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>27889d92-ed07-41b7-9939-36f9cc1f8bf5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>18ea0c72-aad5-4b6a-90d3-f716d29d8b1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>27889d92-ed07-41b7-9939-36f9cc1f8bf5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>8a964b5c-e0d3-4624-a3b8-c11fce8e6f5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>27889d92-ed07-41b7-9939-36f9cc1f8bf5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>id</value>
         <variableId>62f15f6e-2189-41f8-a271-d5b7ce5c31cd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
