<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Processor 2.2 GHz Intel Pentium Dual-Co_65063c</name>
   <tag></tag>
   <elementGuidId>70b2e612-b655-4e2b-8298-c6e1037f182f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.product > div.attributes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='shopping-cart-form']/div/table/tbody/tr[2]/td[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a8b3b491-718d-4c42-9ccf-e6478fd18cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attributes</value>
      <webElementGuid>c45a4592-a71b-4ce2-a09d-f36ba11751b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Processor: 2.2 GHz Intel Pentium Dual-Core E2200RAM: 4GB [+$20.00]HDD: 320 GBOS: Vista Premium [+$60.00]Software: Microsoft Office [+$50.00]Software: Acrobat Reader [+$10.00]</value>
      <webElementGuid>e058fecb-fed7-42a4-9a2c-4ccd16d56713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart-form&quot;)/div[@class=&quot;table-wrapper&quot;]/table[@class=&quot;cart&quot;]/tbody[1]/tr[2]/td[@class=&quot;product&quot;]/div[@class=&quot;attributes&quot;]</value>
      <webElementGuid>a7683b06-cd0f-4f9b-b8af-0b821372263f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shopping-cart-form']/div/table/tbody/tr[2]/td[3]/div</value>
      <webElementGuid>a9d07806-1070-4ed6-b555-eb30d50cbad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build your own computer'])[2]/following::div[1]</value>
      <webElementGuid>ef9303a6-ce60-4ffe-91c7-b0fa6e1a6473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMP_CUST'])[1]/following::div[1]</value>
      <webElementGuid>42df06a6-92f6-407d-a1cb-7f74a97fbad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::div[1]</value>
      <webElementGuid>d6c03097-f94f-4ac6-b4bb-81e12506779d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price:'])[2]/preceding::div[2]</value>
      <webElementGuid>d200de5e-cc5f-4613-ac4d-d7b9dcb7af81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div</value>
      <webElementGuid>ba049d58-0840-473e-aea5-b4d0e3360df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Processor: 2.2 GHz Intel Pentium Dual-Core E2200RAM: 4GB [+$20.00]HDD: 320 GBOS: Vista Premium [+$60.00]Software: Microsoft Office [+$50.00]Software: Acrobat Reader [+$10.00]' or . = 'Processor: 2.2 GHz Intel Pentium Dual-Core E2200RAM: 4GB [+$20.00]HDD: 320 GBOS: Vista Premium [+$60.00]Software: Microsoft Office [+$50.00]Software: Acrobat Reader [+$10.00]')]</value>
      <webElementGuid>4a0829d1-554a-4dbf-b628-00df67896e00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
