<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_shopping cart_close</name>
   <tag></tag>
   <elementGuidId>c367c77f-5e6c-44b9-a536-d59fd5f07280</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bar-notification']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>211ed646-163d-43ca-927d-2e053b106ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>f59fa1bc-4a22-4686-8d7f-addd69da5ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>5f289aca-6316-43c8-97e7-3afe66963c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bar-notification&quot;)/div[@class=&quot;bar-notification success&quot;]/span[@class=&quot;close&quot;]</value>
      <webElementGuid>d8295ff3-3bd5-4f05-95f3-1f7aabadc3d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bar-notification']/div/span</value>
      <webElementGuid>9146c129-657d-4b04-97ae-bf340f9efc86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>ea7cac0c-ac0f-402f-8c29-70e6e0b12d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Close']</value>
      <webElementGuid>39228f08-c716-464b-936f-bc980441e084</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
