<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Microsoft Office 50.00_product_attribute_5</name>
   <tag></tag>
   <elementGuidId>89750fcb-78cd-46a5-adf9-3f67363bce90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_attribute_5_11</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_attribute_5_11']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ede20a76-3fc2-4202-a4a0-206adb1b3bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_attribute_5_11</value>
      <webElementGuid>ddb093db-65cd-493b-9f3d-7ead9b7cdf82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bfea7331-f4c1-4b89-a6d0-dbf0d4ef36e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_attribute_5</value>
      <webElementGuid>e87a7bd0-b7fe-4c3a-8048-34e52e30f7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>87895c33-9166-4300-a886-596798a171a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_attribute_5_11&quot;)</value>
      <webElementGuid>5ce34f0c-c8a8-4081-a0c5-05b66f37a432</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_attribute_5_11']</value>
      <webElementGuid>8f7b4064-e6e6-44dc-bf67-5b9ec2aded95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dd[@id='product_attribute_input_5']/ul/li[2]/input</value>
      <webElementGuid>570360fe-45be-45db-961e-d1dc4fc48fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd[5]/ul/li[2]/input</value>
      <webElementGuid>f7d4380e-19c2-43dd-bcb2-377ebce30a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'product_attribute_5_11' and @type = 'checkbox' and @name = 'product_attribute_5']</value>
      <webElementGuid>f029e228-64e5-4e3e-b71b-bf4bce554d69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
