<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select2 GB4GB 20.008GB 60.00</name>
   <tag></tag>
   <elementGuidId>7f2dad76-62be-475c-b3a5-a6b4ce148ad9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_attribute_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='product_attribute_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bf74d01f-db6c-4c42-88f1-745d714d93a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attr</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5a68149b-0a48-4886-8a0a-d66b22d3c539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_attribute_2</value>
      <webElementGuid>25f910f2-e399-4863-8332-d97eaadb0427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_attribute_2</value>
      <webElementGuid>337146c0-b51b-4616-b925-9df73549a659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select2 GB4GB [+$20.00]8GB [+$60.00]</value>
      <webElementGuid>82c34f43-da4d-4288-a919-81ce7a162d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_attribute_2&quot;)</value>
      <webElementGuid>cbeb5473-5570-4da1-ba31-009b0c7dc2cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='product_attribute_2']</value>
      <webElementGuid>b91b0b11-49b9-4404-9de4-0735aab23cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dd[@id='product_attribute_input_2']/select</value>
      <webElementGuid>1837b2ee-24f9-4250-9d14-6c52ba28546a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>6762b04d-d36a-4b6b-b3a3-020e5b050bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RAM'])[1]/following::select[1]</value>
      <webElementGuid>c72c483b-1231-4de2-adcf-6fdabd6ccf39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HDD'])[1]/preceding::select[1]</value>
      <webElementGuid>028068b1-b3d5-4bf9-bd50-ee267eb71ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::select[1]</value>
      <webElementGuid>a075bd8e-52c6-4f5e-8694-367651bf2839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd[2]/select</value>
      <webElementGuid>3b014bb0-d2f4-4116-856e-2372c50d15a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'product_attribute_2' and @id = 'product_attribute_2' and (text() = 'Please select2 GB4GB [+$20.00]8GB [+$60.00]' or . = 'Please select2 GB4GB [+$20.00]8GB [+$60.00]')]</value>
      <webElementGuid>3f5f12e8-674d-4f1b-9ba1-45dd26c2b951</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
