<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qty_itemquantity11229</name>
   <tag></tag>
   <elementGuidId>4b829897-6fc1-4a7f-8ca8-ba15e2e33d5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itemquantity11229</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='itemquantity11229']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8bdd990b-b15b-43ab-9c0b-79366211eb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemquantity11229</value>
      <webElementGuid>3a74ed95-fbf2-4555-bacf-b354dd8b24b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemquantity11229</value>
      <webElementGuid>117df039-551b-4583-9b22-692c6dddcb77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5efe952d-3724-4c72-9685-83f109ca7073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dee3dddb-e34f-4de2-9043-aee5ced1909e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qty-input</value>
      <webElementGuid>8a94c130-1d54-4402-a84e-28da67be02d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Qty.</value>
      <webElementGuid>6168eaeb-13bb-40af-86ba-78e21e304dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c64b16d3-7159-42b1-a567-cb0bcf464fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemquantity11229&quot;)</value>
      <webElementGuid>e85217ed-7a18-4f76-b2ac-e503df9db174</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='itemquantity11229']</value>
      <webElementGuid>15b655f0-ba6e-4949-ad94-8c62f45972c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shopping-cart-form']/div/table/tbody/tr/td[5]/input</value>
      <webElementGuid>3b5327e6-b369-481f-971c-74ea388df66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>7dcddccd-8a9d-4337-8898-4ba2c6d636de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'itemquantity11229' and @id = 'itemquantity11229' and @type = 'text']</value>
      <webElementGuid>0231356f-a7c3-4e3f-8d7b-d6c43a537fd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
