<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Please accept the terms of service before_7d8c5c</name>
   <tag></tag>
   <elementGuidId>78fae638-08d6-4904-86e3-b024dcaf818a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='terms-of-service-warning-box']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>56c733cb-b21d-4143-9415-66472981d025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please accept the terms of service before the next step.</value>
      <webElementGuid>1c6d52c7-2d46-4ba2-8a03-82fffae3a069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terms-of-service-warning-box&quot;)/p[1]</value>
      <webElementGuid>ca5479a9-1a7c-4b75-9808-5536a73d8135</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='terms-of-service-warning-box']/p</value>
      <webElementGuid>e36cd44b-6101-42ab-8d95-d73f6d30da9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::p[1]</value>
      <webElementGuid>2fd8c469-581f-4c1f-9ce7-3b9a296f3ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of service'])[1]/following::p[1]</value>
      <webElementGuid>14e85fdd-bdbf-4f9b-9522-6fe9418c43af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please accept the terms of service before the next step.']/parent::*</value>
      <webElementGuid>bc6669be-c638-43fc-88a4-c718d3ab2f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>20489830-3228-4300-8349-181aa4dde475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Please accept the terms of service before the next step.' or . = 'Please accept the terms of service before the next step.')]</value>
      <webElementGuid>8d555731-cc24-4e27-b8cc-d88067416ade</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
