<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address.Address1</name>
   <tag></tag>
   <elementGuidId>f6238f57-ffbf-4ba4-8a2d-13955ff8e2ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'Address_Address1')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Address_Address1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf9aaf1c-eb8e-464f-a9e7-0db9f384174b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>48353256-b47b-41f4-9103-d366fd9b3d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5384cb16-8362-4d3f-bb2d-c1ff1dfab940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Street address is required</value>
      <webElementGuid>c61032db-d6f8-48c2-8298-fd634f71a8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Address_Address1</value>
      <webElementGuid>b339bd87-fab1-43c2-80fa-e15a7f14ee5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Address.Address1</value>
      <webElementGuid>375571d4-da58-45d6-85ed-f41c028451c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5a Trung Kính</value>
      <webElementGuid>42dfd14c-3b3f-4a03-a8ba-f5c594e3e705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Address_Address1&quot;)</value>
      <webElementGuid>5ef5de04-12b6-4a58-a30a-06cd5a953b1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Address_Address1']</value>
      <webElementGuid>5c4e078a-89f3-415d-bf33-6581cb57feed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>5054d761-7fed-436b-ac74-ce73e3dbc044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Address_Address1' and @name = 'Address.Address1']</value>
      <webElementGuid>f5951127-48b8-42ce-afcd-0f16d3809feb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
