<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address.ZipPostalCode</name>
   <tag></tag>
   <elementGuidId>0ec07a34-6666-4f32-9f9d-ff0595b5c9ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Address_ZipPostalCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Address_ZipPostalCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>683f545f-4d8f-413d-85c5-39c47bba6095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6b107661-378b-4e9f-bbf1-2a5b7f5be7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>88d21ba3-cf20-4e1a-b85e-d05a1c91d966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Zip / postal code is required</value>
      <webElementGuid>47cf6d89-3969-4e55-91cc-10afeb0d9491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Address_ZipPostalCode</value>
      <webElementGuid>0be83f97-b863-4ab0-aa51-9e44e8139768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Address.ZipPostalCode</value>
      <webElementGuid>b3418250-76a3-4817-8081-3a83af5b9cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2133456</value>
      <webElementGuid>dfe96a0b-1e72-4d8a-b7d2-54dc950597a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Address_ZipPostalCode&quot;)</value>
      <webElementGuid>795f2f0f-f6c3-48a0-b1c1-fb75404caebb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Address_ZipPostalCode']</value>
      <webElementGuid>6b11a40f-4053-4a1f-a25f-d76cc5c62cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/input</value>
      <webElementGuid>65ba0783-c38f-4881-9ea7-c7f75989c451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Address_ZipPostalCode' and @name = 'Address.ZipPostalCode']</value>
      <webElementGuid>fd55db8b-fdb7-4750-889a-c1a8e4b35fa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
