<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address.Address1</name>
   <tag></tag>
   <elementGuidId>f6238f57-ffbf-4ba4-8a2d-13955ff8e2ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Address_Address1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Address_Address1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac0ada09-f014-4cae-b59c-d4b556f124cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5759e0dc-c5a8-4dfa-a894-9399fe256926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cda0da2b-4383-4f72-b52d-1dfb860e2382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Street address is required</value>
      <webElementGuid>92618512-5bc9-4c1f-923d-a609ba156187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Address_Address1</value>
      <webElementGuid>42d69c06-65d0-4aa3-9112-dc42fed58b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Address.Address1</value>
      <webElementGuid>6901c9c3-d089-46b9-a7e8-c8921485f78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5a Trung Kính</value>
      <webElementGuid>16711c08-633c-46a3-8855-c11d01fe2805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Address_Address1&quot;)</value>
      <webElementGuid>d75ac28a-f686-43df-a018-7d4e61547aae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Address_Address1']</value>
      <webElementGuid>59512552-099e-47d5-9754-bcb8b20b2148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>7b4e5e12-5c3f-4972-b6bf-cc8935a6f1bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Address_Address1' and @name = 'Address.Address1']</value>
      <webElementGuid>92687c07-5702-4842-87d4-dd8ed225a138</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
