<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address.Email</name>
   <tag></tag>
   <elementGuidId>bcec3dd9-bfdc-4d7e-a745-5c36e750cc9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Address_Email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Address_Email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4eaf513-7841-43c4-a826-2be55a7dfa22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>5bf9bfd9-1034-41df-8de6-37f0fb45a464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9438f83c-66f1-4798-8203-bbe470738533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-email</name>
      <type>Main</type>
      <value>Wrong email</value>
      <webElementGuid>358335a9-f1ee-4f96-99d0-c7874831bfec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Email is required.</value>
      <webElementGuid>2c9b3e85-5fe8-4bb5-987e-fb008c5402b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Address_Email</value>
      <webElementGuid>5603346d-addc-4f96-92c9-4080caed0ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Address.Email</value>
      <webElementGuid>3d9b2929-3eaf-496d-85ec-0ed5caee9836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>yyangduong@gmail.com</value>
      <webElementGuid>3794740c-3daf-45c3-bd46-db0ab697b14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Address_Email&quot;)</value>
      <webElementGuid>dcece4f1-9e8c-4be2-b580-d0570cad9f68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Address_Email']</value>
      <webElementGuid>7e2bef04-a1d0-4cf8-a9ee-db214218398b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>cc0580b9-3c40-495b-84f9-0fe07f2ab7a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'Address_Email' and @name = 'Address.Email']</value>
      <webElementGuid>6cbc298e-99ca-45ad-bbd6-150c6c5edfc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
