<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address.First name</name>
   <tag></tag>
   <elementGuidId>9afc8aae-fcdb-4cc6-9f7a-dc717c729909</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Address_FirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Address_FirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48ea8034-24c3-44e7-864f-6ed16f0c3ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af42daf8-de2a-43c1-867a-8b36e236bb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>58da8409-22bb-4088-b9bc-e75217460c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>First name is required.</value>
      <webElementGuid>15953491-abba-4d84-8292-7a623fa0650d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Address_FirstName</value>
      <webElementGuid>529ec81a-7881-4284-9362-9151ecca1bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Address.FirstName</value>
      <webElementGuid>96528cfd-3a9b-41a7-8c83-16fca045b8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Nguyễn</value>
      <webElementGuid>5d51a6c8-2b20-47e2-b42b-4d4002f51705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Address_FirstName&quot;)</value>
      <webElementGuid>cb9b0b76-b83b-4766-8aa7-e1c0d0b3a39d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Address_FirstName']</value>
      <webElementGuid>83c6c034-411a-4316-88d3-1eb7fe0aecc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>d141ae8a-0228-4043-bd6c-3c1ef1e0e87b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Address_FirstName' and @name = 'Address.FirstName']</value>
      <webElementGuid>108e3d3c-fb45-46f8-a590-3e091086bf3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
