<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_InfoPhone</name>
   <tag></tag>
   <elementGuidId>9e8fb377-62c4-47d8-945f-38ef102ae840</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//li[@class='phone'])[${i}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c09b49ab-1b9c-4336-a93a-19c0724d7be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>4c4c77fe-d8d1-473f-a28d-53050acf66dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phone number: jfmygt</value>
      <webElementGuid>112b9599-e65a-4315-8f9a-da58d6e69398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;html-account-page html-address-list-page&quot;]/body[1]/div[@class=&quot;master-wrapper-page&quot;]/div[@class=&quot;master-wrapper-content&quot;]/div[@class=&quot;master-column-wrapper&quot;]/div[@class=&quot;center-2&quot;]/div[@class=&quot;page account-page address-list-page&quot;]/div[@class=&quot;page-body&quot;]/div[@class=&quot;address-list&quot;]/div[@class=&quot;section address-item&quot;]/ul[@class=&quot;info&quot;]/li[@class=&quot;phone&quot;]</value>
      <webElementGuid>235d7334-d163-423d-b9f3-2fc54f2a03ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[1]/following::li[1]</value>
      <webElementGuid>a1663a78-21cf-4092-8e24-1a5a191e7783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fax number:'])[1]/preceding::li[1]</value>
      <webElementGuid>e93ea6e5-b318-4d05-b638-12cff6c34d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='jfmygt']/parent::*</value>
      <webElementGuid>3836abff-4f06-4181-8c49-3777d92e2fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[3]</value>
      <webElementGuid>91a88041-e60a-4cca-805d-eaa212d49f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Phone number: jfmygt' or . = 'Phone number: jfmygt')]</value>
      <webElementGuid>acd19568-4323-4471-9f16-3ca403c641c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
