<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_InfoEmail</name>
   <tag></tag>
   <elementGuidId>f097094c-42fa-4150-b214-b2f5af123885</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@class='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>aba9744c-6379-42bb-a5d5-7460cf9151ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e20ac367-4b80-4b61-ab09-a89287835e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email: yyangduong@gmail.com</value>
      <webElementGuid>55e4c20f-16f7-4258-9aeb-e84807188620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;html-account-page html-address-list-page&quot;]/body[1]/div[@class=&quot;master-wrapper-page&quot;]/div[@class=&quot;master-wrapper-content&quot;]/div[@class=&quot;master-column-wrapper&quot;]/div[@class=&quot;center-2&quot;]/div[@class=&quot;page account-page address-list-page&quot;]/div[@class=&quot;page-body&quot;]/div[@class=&quot;address-list&quot;]/div[@class=&quot;section address-item&quot;]/ul[@class=&quot;info&quot;]/li[@class=&quot;email&quot;]</value>
      <webElementGuid>68bf477a-bc65-4788-9afb-3e4ef53a9cb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nguyễn Hường'])[2]/following::li[1]</value>
      <webElementGuid>deab15b9-32a6-414a-a5a4-89be73fc1a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nguyễn Hường'])[1]/following::li[2]</value>
      <webElementGuid>23daa6e2-35de-441c-a06e-7275c3f705c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='yyangduong@gmail.com']/parent::*</value>
      <webElementGuid>e0a776f1-af55-4a15-8029-c057a8d895fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[2]</value>
      <webElementGuid>c8d8df40-2c44-4cb8-bb6b-cbb998650b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Email: yyangduong@gmail.com' or . = 'Email: yyangduong@gmail.com')]</value>
      <webElementGuid>3b750bcc-7f5e-447a-82cb-fc54b6e0cb4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
