<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_InfoEmail</name>
   <tag></tag>
   <elementGuidId>f097094c-42fa-4150-b214-b2f5af123885</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//li[@class='email'])[${i}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b4016315-2af9-4152-8c07-2fe47c2e9b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>928582ac-7544-4128-aa5c-3b0706b2c87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email: yyangduong@gmail.com</value>
      <webElementGuid>827d2a7b-f137-41b8-987b-57a1f04486d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;html-account-page html-address-list-page&quot;]/body[1]/div[@class=&quot;master-wrapper-page&quot;]/div[@class=&quot;master-wrapper-content&quot;]/div[@class=&quot;master-column-wrapper&quot;]/div[@class=&quot;center-2&quot;]/div[@class=&quot;page account-page address-list-page&quot;]/div[@class=&quot;page-body&quot;]/div[@class=&quot;address-list&quot;]/div[@class=&quot;section address-item&quot;]/ul[@class=&quot;info&quot;]/li[@class=&quot;email&quot;]</value>
      <webElementGuid>1760efc3-4589-438d-9917-eea9e40942b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nguyễn Hường'])[2]/following::li[1]</value>
      <webElementGuid>efac1ec0-214d-40b6-8b5b-ba1c5a1e16be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nguyễn Hường'])[1]/following::li[2]</value>
      <webElementGuid>a5be7d6c-a9e3-45df-a553-995980c6e714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='yyangduong@gmail.com']/parent::*</value>
      <webElementGuid>bf65e156-cae6-4556-b813-4856614d7d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[2]</value>
      <webElementGuid>5a4379ec-d8d8-4c9e-8fa7-5a9159f50ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Email: yyangduong@gmail.com' or . = 'Email: yyangduong@gmail.com')]</value>
      <webElementGuid>ffbb612d-c60b-47e8-b649-b646125cc10d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
