<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_My account_close</name>
   <tag></tag>
   <elementGuidId>f8f4d5c5-912a-4e8f-aa59-b639453e1cfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bar-notification']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>34d70b40-eec3-40e0-bf43-3a9da0f7a823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>47b86092-5fe9-4002-b709-6cdc607f1d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>a75e81af-2725-4981-9c91-36c595fa695b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bar-notification&quot;)/div[@class=&quot;bar-notification success&quot;]/span[@class=&quot;close&quot;]</value>
      <webElementGuid>d0726629-2b3f-485c-9235-adec925c59c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bar-notification']/div/span</value>
      <webElementGuid>3b44885b-9548-432f-a9a5-d5ae95ce3cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>45512eb1-6d79-4ad3-8f3b-d1d8c9328cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Close']</value>
      <webElementGuid>d32c42f8-7e73-4d56-901e-43cd752eb7c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
