<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address.First name</name>
   <tag></tag>
   <elementGuidId>9afc8aae-fcdb-4cc6-9f7a-dc717c729909</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Address_FirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'Address_FirstName')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e672652d-90eb-4566-adf5-dbf30a8917af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>686b9ff5-0eae-4ea9-b2cc-6b8fea443e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6c8523ea-160e-4d38-9c6c-1335f8664ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>First name is required.</value>
      <webElementGuid>a5f89b11-0c5b-4108-a9cb-116cc824795e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Address_FirstName</value>
      <webElementGuid>af9157a4-322c-4b0d-bf00-d7e11c0bfcea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Address.FirstName</value>
      <webElementGuid>e4598fb0-d931-46e3-950b-ab849a63aa7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Nguyễn</value>
      <webElementGuid>3dad893d-162c-4d04-8ee6-473d16f592f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Address_FirstName&quot;)</value>
      <webElementGuid>229bea2c-e030-4855-b1e1-f5042f6e8072</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Address_FirstName']</value>
      <webElementGuid>9be6612d-dc1a-43a6-95db-f8373237b656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>04b8e420-545f-47a2-87c3-e4ff66a8bc2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Address_FirstName' and @name = 'Address.FirstName']</value>
      <webElementGuid>d4e58e50-c704-4178-8460-f51e13ddca1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
