<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address.PhoneNumber</name>
   <tag></tag>
   <elementGuidId>39d64013-53d5-4b7f-9f79-3d7c7424a982</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Address_PhoneNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'Address_PhoneNumber')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d63d9cd5-097d-47a3-ac0c-19ba007e2c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>d6c2ab82-66e8-4c71-96f5-f657512ffe10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1b72804f-2539-420c-9b59-f7c495885561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Phone is required</value>
      <webElementGuid>94dd1a61-48b6-4752-a04a-82fa51552436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Address_PhoneNumber</value>
      <webElementGuid>72598b9b-fffd-4c10-b8f8-b6f911af790c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Address.PhoneNumber</value>
      <webElementGuid>3cb0fff7-43ce-4f09-a4c4-2d6b1508a3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>jfmygt</value>
      <webElementGuid>189832e8-db36-43c6-b5d6-9fb9d60650c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Address_PhoneNumber&quot;)</value>
      <webElementGuid>3072b931-02e5-454a-ace1-99c3a5583b2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Address_PhoneNumber']</value>
      <webElementGuid>520a0128-d375-4380-a8fa-266b33d22848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>9c90739b-930b-4833-8dab-017945bb5900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'Address_PhoneNumber' and @name = 'Address.PhoneNumber']</value>
      <webElementGuid>8212d8b3-dacc-4d67-9345-49344201abf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
