<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address.Email</name>
   <tag></tag>
   <elementGuidId>bcec3dd9-bfdc-4d7e-a745-5c36e750cc9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Address_Email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'Address_Email')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2cd3ad01-f536-45eb-9572-9757cf96caaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>49daa65d-8454-474f-9586-5f3fd386dd35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>99f3ec54-57cb-486f-9846-6379761b25ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-email</name>
      <type>Main</type>
      <value>Wrong email</value>
      <webElementGuid>1f7730ef-f753-4da8-95be-e8a8a400990a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Email is required.</value>
      <webElementGuid>ca29becd-ff34-44eb-b748-c1652160b69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Address_Email</value>
      <webElementGuid>1a1f455a-0d47-46c0-8f67-dcba474aec5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Address.Email</value>
      <webElementGuid>9f0b664a-a734-4028-ba38-8b3e9814a3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>yyangduong@gmail.com</value>
      <webElementGuid>6dd3c666-97f4-4b29-80ef-0d261db8d758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Address_Email&quot;)</value>
      <webElementGuid>7065b7d1-36d7-4097-b472-c691888b36bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Address_Email']</value>
      <webElementGuid>0444ede1-9f8b-4e50-90df-05aeb2fdf6ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>938158ce-55ff-4fd6-bc32-4ce14791860f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'Address_Email' and @name = 'Address.Email']</value>
      <webElementGuid>6cbca1a6-42a8-4664-a4e8-20e46c91064c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
