<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address.ZipPostalCode</name>
   <tag></tag>
   <elementGuidId>0ec07a34-6666-4f32-9f9d-ff0595b5c9ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Address_ZipPostalCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'Address_ZipPostalCode')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4045ef5-e78c-42a5-9054-2dee00ff74bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fcfa059c-a8a3-4fab-9514-6d762a5b021f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>88872e7d-7a39-487e-ab2d-f864d7a6886b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Zip / postal code is required</value>
      <webElementGuid>fdaec556-6287-4f41-bcdf-89dab9f63aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Address_ZipPostalCode</value>
      <webElementGuid>d0b35236-3780-409d-8e9c-da6442b875aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Address.ZipPostalCode</value>
      <webElementGuid>edab1390-917a-4ecc-b85c-76a9144d9de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2133456</value>
      <webElementGuid>07ff5bd5-5eed-4b52-8b98-2df244549fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Address_ZipPostalCode&quot;)</value>
      <webElementGuid>aa67c2b3-d111-4f1f-988c-92840be9b7cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Address_ZipPostalCode']</value>
      <webElementGuid>d6a0af69-ac5b-4528-9087-d1863bcf3d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/input</value>
      <webElementGuid>c4c0cf07-3190-48c1-9531-1b71bcf0af18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Address_ZipPostalCode' and @name = 'Address.ZipPostalCode']</value>
      <webElementGuid>53cf9ef0-5baa-4cd8-bf9b-989c3d8f1e4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
