<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_City is required</name>
   <tag></tag>
   <elementGuidId>2438a2fd-daec-4d99-996d-107ce20064d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Address_City-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='Address_City-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cbf4c045-fab2-43a7-a320-bd34a67f41ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Address_City-error</value>
      <webElementGuid>2318748a-c3ac-424c-bbff-fd7e3a2e818f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>City is required</value>
      <webElementGuid>d6b6f71b-6850-42f1-8a8c-473d5c3780c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Address_City-error&quot;)</value>
      <webElementGuid>06751908-6bb9-4d57-8558-ac6b087a97c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='Address_City-error']</value>
      <webElementGuid>040d02f7-049e-49b2-b6db-05c5b42fa038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::span[2]</value>
      <webElementGuid>3ae360fe-2c4b-4fc5-8624-18d6017c9352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City:'])[1]/following::span[3]</value>
      <webElementGuid>69a3a52b-268b-4ba9-81d3-9cb8cefac032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address 1:'])[1]/preceding::span[1]</value>
      <webElementGuid>f4734e0e-315b-476c-af4c-bccb4b2c044b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::span[1]</value>
      <webElementGuid>0a5d8f4a-b996-4d2e-abe0-6d611e4083eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='City is required']/parent::*</value>
      <webElementGuid>ee0763f6-91f8-404c-a23d-4e27122deab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/span[2]/span</value>
      <webElementGuid>2a1c4d00-964d-400e-9aa3-b0e7d2db6509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'Address_City-error' and (text() = 'City is required' or . = 'City is required')]</value>
      <webElementGuid>6e5065f2-c069-4c76-a516-7ca5f7cd9512</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
