<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Last name is required</name>
   <tag></tag>
   <elementGuidId>e7817e01-f435-42ed-bbe1-04eac8603217</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Address_LastName-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='Address_LastName-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4cb55f6d-1fd7-473e-9a15-f383deb8d965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Address_LastName-error</value>
      <webElementGuid>8d7f5b0a-55bf-480f-9a1b-28d1936e0d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Last name is required.</value>
      <webElementGuid>b2454786-6c03-41a1-9524-4ebe3557307e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Address_LastName-error&quot;)</value>
      <webElementGuid>7b23df30-5d98-40ac-833e-37eae8e520b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='Address_LastName-error']</value>
      <webElementGuid>883a1b03-d5b8-4bdb-85ba-92c412df8f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[2]</value>
      <webElementGuid>42c211bf-7ec2-4875-8de6-6c9860b84544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last name:'])[1]/following::span[3]</value>
      <webElementGuid>c6f7953e-fd64-4acc-ae4d-882e8bb6d4b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[1]/preceding::span[1]</value>
      <webElementGuid>9f3d7c28-2d8e-43b8-a193-d490efd75376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::span[1]</value>
      <webElementGuid>ea06ba92-19f5-44fe-816f-ef62fca0d58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Last name is required.']/parent::*</value>
      <webElementGuid>fadac6ee-78f6-4ff8-86a1-b17829342c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]/span</value>
      <webElementGuid>d5386548-09a7-4058-bf3c-f3fc2536827c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'Address_LastName-error' and (text() = 'Last name is required.' or . = 'Last name is required.')]</value>
      <webElementGuid>8a2d3134-adc9-4c1b-81ae-34e8201929af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
