<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Street address is required</name>
   <tag></tag>
   <elementGuidId>688f0e6f-1232-45d9-8ba3-430adbf6ac10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Address_Address1-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='Address_Address1-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7826826c-6b56-49bb-a958-5296693f30fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Address_Address1-error</value>
      <webElementGuid>6529da6c-7689-4fb5-8b1d-429d4bad4132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Street address is required</value>
      <webElementGuid>c68e6658-d219-4f75-8902-4b620c31f6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Address_Address1-error&quot;)</value>
      <webElementGuid>37c2d357-3da2-46f7-b751-0216d8077cdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='Address_Address1-error']</value>
      <webElementGuid>e927919e-6247-4c17-8cfe-3dda8d067a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::span[2]</value>
      <webElementGuid>34a10bd2-a973-45c5-bd1f-7b5f6ed5cd49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address 1:'])[1]/following::span[3]</value>
      <webElementGuid>222a4d81-7450-4267-8fa9-c8985d8a0186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address 2:'])[1]/preceding::span[1]</value>
      <webElementGuid>e877d378-34c2-496c-bc85-ade683b88ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip / postal code:'])[1]/preceding::span[2]</value>
      <webElementGuid>129af799-8b9e-4068-bb07-351dd34d7e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Street address is required']/parent::*</value>
      <webElementGuid>7abe6dda-7dd4-4bbc-8a74-a5ab41d14864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/span[2]/span</value>
      <webElementGuid>f6c63c1c-5db3-4281-941c-e814b85350ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'Address_Address1-error' and (text() = 'Street address is required' or . = 'Street address is required')]</value>
      <webElementGuid>58e2584c-6f50-44a9-b817-8c62c0588376</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
