<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_25 Virtual Gift Card</name>
   <tag></tag>
   <elementGuidId>ac20fe69-1009-4485-ac2a-d4feed802402</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='shopping-cart-form']/div/table/tbody/tr[3]/td[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8a753eaf-ec70-41f5-a0e5-bd03419f11be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/25-virtual-gift-card</value>
      <webElementGuid>4624dfca-b1cf-44a7-ad98-887fde68816d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-name</value>
      <webElementGuid>9d29d6ac-fea8-4862-b2b8-bce860f0126f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$25 Virtual Gift Card</value>
      <webElementGuid>f6e5788d-8ce1-469c-98fd-abde51b1b556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart-form&quot;)/div[@class=&quot;table-wrapper&quot;]/table[@class=&quot;cart&quot;]/tbody[1]/tr[3]/td[@class=&quot;product&quot;]/a[@class=&quot;product-name&quot;]</value>
      <webElementGuid>eb48d012-e087-455d-b1ce-33d5914d253e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shopping-cart-form']/div/table/tbody/tr[3]/td[3]/a</value>
      <webElementGuid>9cd60d24-86c3-4d8b-89e1-52523e2f8b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'$25 Virtual Gift Card')])[2]</value>
      <webElementGuid>e13699c8-519d-4abf-b039-74b470ce5d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VG_CR_025'])[1]/following::a[2]</value>
      <webElementGuid>0c6b36e2-95d8-4281-bd7e-d3dab4f4fc1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SKU:'])[3]/following::a[2]</value>
      <webElementGuid>9fa90ad1-6f9f-43a5-9729-1378886130d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From: Luyen &lt;luyen@gmail.com>For: Nguyen Hai Luyen &lt;nhl@gmail.com>'])[2]/preceding::a[1]</value>
      <webElementGuid>24c34e48-e704-492c-82b2-b4206c8b0fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/preceding::a[1]</value>
      <webElementGuid>e127cd65-e0e0-4888-9ab9-ca8ee02ab7de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/25-virtual-gift-card')])[4]</value>
      <webElementGuid>d3446203-1b3d-4a5e-85dc-a38afe00d506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/a</value>
      <webElementGuid>ed549b40-b8c5-403a-b2e5-6edb916da74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/25-virtual-gift-card' and (text() = '$25 Virtual Gift Card' or . = '$25 Virtual Gift Card')]</value>
      <webElementGuid>70706f28-b487-4ef2-924c-66af3b253500</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
