<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ProductName</name>
   <tag></tag>
   <elementGuidId>9d05dc4b-e328-4e4b-b926-8bccbcef8a59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.product-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[${index}]//a[@class='product-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2985a0ef-3743-493f-9c98-d81d59845123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/htc-one-m8-android-l-50-lollipop</value>
      <webElementGuid>b5fdf965-6bae-4b51-adf7-8b5854406410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-name</value>
      <webElementGuid>913e9db3-f32f-4831-900a-3f4c40b48189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HTC One M8 Android L 5.0 Lollipop</value>
      <webElementGuid>2d007304-c875-4157-a1e6-fefcca9a0c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart-form&quot;)/div[@class=&quot;table-wrapper&quot;]/table[@class=&quot;cart&quot;]/tbody[1]/tr[1]/td[@class=&quot;product&quot;]/a[@class=&quot;product-name&quot;]</value>
      <webElementGuid>bf61e49d-f682-4c38-aa43-0481e00d8814</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shopping-cart-form']/div/table/tbody/tr/td[3]/a</value>
      <webElementGuid>a45df2da-fc96-4b13-a261-42e51ab0c277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'HTC One M8 Android L 5.0 Lollipop')])[2]</value>
      <webElementGuid>8e6953b5-98c4-46b2-8624-6204eacd4293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M8_HTC_5L'])[1]/following::a[2]</value>
      <webElementGuid>1a17961f-1b48-44c2-9df1-5a4cc2367ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SKU:'])[1]/following::a[2]</value>
      <webElementGuid>e6be029e-62d4-498c-af9d-2448a7436a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price:'])[1]/preceding::a[1]</value>
      <webElementGuid>c857a9c3-fe22-4fbb-a4a5-958584100018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$245.00'])[2]/preceding::a[1]</value>
      <webElementGuid>4a1792ac-dd53-4564-a815-f9d3b9de223b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/htc-one-m8-android-l-50-lollipop')])[4]</value>
      <webElementGuid>313ad1ae-b5f5-4da9-8814-ec09a1420d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>70f8ffa5-1095-46d6-957f-3560a99596a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/htc-one-m8-android-l-50-lollipop' and (text() = 'HTC One M8 Android L 5.0 Lollipop' or . = 'HTC One M8 Android L 5.0 Lollipop')]</value>
      <webElementGuid>9c9a7481-ffe3-4f44-8b5b-bf7ccecbc797</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
