<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_From Luyen luyengmail.comFor Nguyen Hai_1efad2</name>
   <tag></tag>
   <elementGuidId>21c9c315-8b89-4b59-92ab-0af028ec99c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='shopping-cart-form']/div/table/tbody/tr[3]/td[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4cc85b17-4318-44e6-b2e7-45755733846e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attributes</value>
      <webElementGuid>0587ba1d-9e37-4ce7-93d0-ecd05e5d96ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>From: Luyen &lt;luyen@gmail.com>For: Nguyen Hai Luyen &lt;nhl@gmail.com></value>
      <webElementGuid>fe151b92-7981-4e31-855b-5c8884bf31e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart-form&quot;)/div[@class=&quot;table-wrapper&quot;]/table[@class=&quot;cart&quot;]/tbody[1]/tr[3]/td[@class=&quot;product&quot;]/div[@class=&quot;attributes&quot;]</value>
      <webElementGuid>f0a91272-6f6c-476e-9dba-f1474bacbd11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shopping-cart-form']/div/table/tbody/tr[3]/td[3]/div</value>
      <webElementGuid>5979c180-3812-45fc-afdd-757d6d9d7941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$25 Virtual Gift Card'])[2]/following::div[1]</value>
      <webElementGuid>fb2237ce-738d-4872-960e-6da4042a087f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VG_CR_025'])[1]/following::div[1]</value>
      <webElementGuid>eb3c3131-c8a9-4009-961c-85cf277b4ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/preceding::div[1]</value>
      <webElementGuid>cd146217-2b3f-4556-9e6d-9c8d115d6a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price:'])[3]/preceding::div[2]</value>
      <webElementGuid>ec881969-0d7e-4ae2-9b60-5e693223c015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div</value>
      <webElementGuid>2b95ea1e-36e4-4f2d-88bd-ea3b23b6ca84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'From: Luyen &lt;luyen@gmail.com>For: Nguyen Hai Luyen &lt;nhl@gmail.com>' or . = 'From: Luyen &lt;luyen@gmail.com>For: Nguyen Hai Luyen &lt;nhl@gmail.com>')]</value>
      <webElementGuid>4467f7b7-e224-4c3d-9ac0-4242af209e42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
