<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Quantity</name>
   <tag></tag>
   <elementGuidId>a002692c-afcd-4d09-ab54-c4931f8938ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_enteredQuantity_18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'product_enteredQuantity')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a41df6b-af6a-41c5-bf3b-0cf02147ebf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_enteredQuantity_18</value>
      <webElementGuid>e24c798d-6e19-4d61-8b13-0240c262b14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qty-input</value>
      <webElementGuid>6fe4ae14-0e68-4beb-b7a1-4c7e28ad6901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eca6b35e-2408-4173-9420-864563950448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter a quantity</value>
      <webElementGuid>18c74513-2780-4feb-81bd-aba8db704c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a94f1aac-1035-4958-be39-bbc18d9a0112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Qty field is required.</value>
      <webElementGuid>da4aeec4-3d2b-4df3-8ccf-ebb91e1bb243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addtocart_18.EnteredQuantity</value>
      <webElementGuid>f2d0183d-876f-4ba4-8b93-4a375be5389a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d1d7e202-bb97-43fb-a69a-0cc9fa153230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_enteredQuantity_18&quot;)</value>
      <webElementGuid>e5f1c534-88bd-4772-9c36-8d91bcb3671f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_enteredQuantity_18']</value>
      <webElementGuid>caf6235b-89cf-481a-8dd2-73a8121c097c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div[2]/div/div[2]/div[6]/div/input</value>
      <webElementGuid>64140c15-1a49-44d5-a78f-0eed8966b791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>377fe7d0-9f0b-4592-8d81-e0582ffc6be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'product_enteredQuantity_18' and @type = 'text' and @name = 'addtocart_18.EnteredQuantity']</value>
      <webElementGuid>afefe7a3-12c6-48b2-bb33-200bae5b9243</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
