<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Try it</name>
   <tag></tag>
   <elementGuidId>7d95761e-24e6-43b4-83dd-2f3de09119c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='myFunction()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4aa12aa9-d113-48a7-a257-9d91bf03bfd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>myFunction()</value>
      <webElementGuid>631b4145-1ab8-49cd-bde9-19f11023cc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Try it</value>
      <webElementGuid>668fa385-737c-4f16-89a8-ac5f66e54378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/button[1]</value>
      <webElementGuid>db0cca7f-5c80-44dc-a967-13dd9e9df1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_W3Schools Tryit Editor/iframe__iframeResult</value>
      <webElementGuid>a2eb8525-7600-4950-bae2-a3d017e3a215</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='myFunction()']</value>
      <webElementGuid>31459a5e-03b9-4269-be2a-751e44e314e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The alert() Method'])[1]/following::button[1]</value>
      <webElementGuid>7dc28e42-9c51-44fc-803f-3b05ffc1b354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Window Object'])[1]/following::button[1]</value>
      <webElementGuid>db0d3689-e06a-47eb-8dbd-3dd5e4d459cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/html[1]/body[1]/button[1]'])[1]/preceding::button[1]</value>
      <webElementGuid>1b9e4ac5-80b9-433c-b56d-85bebacb3ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Try it']/parent::*</value>
      <webElementGuid>fccb9154-3154-4180-8010-4844e8404e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0e60cfb5-b401-4d91-a104-71e9825fd0a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Try it' or . = 'Try it')]</value>
      <webElementGuid>da496254-b6be-4ce2-b319-cbfc2f3c3d7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
