<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_5Payment information</name>
   <tag></tag>
   <elementGuidId>7aab75be-cef7-4c6f-a3b8-395b543d5a13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#opc-payment_info > div.step-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='opc-payment_info']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7290df0b-017b-44f7-8a0d-857b619ec6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>step-title</value>
      <webElementGuid>3c3f71dc-47b5-4fef-bb79-63b967826a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5Payment information</value>
      <webElementGuid>ce72cd28-bb48-4ac4-acd3-d4c8325f7689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc-payment_info&quot;)/div[@class=&quot;step-title&quot;]</value>
      <webElementGuid>cb69cce7-1cb0-4280-949b-fe1480a01c1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='opc-payment_info']/div</value>
      <webElementGuid>b8f8c305-7af2-4d91-bb6b-7dbb94fe2b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading next step...'])[4]/following::div[1]</value>
      <webElementGuid>2af87350-830d-4e7c-904a-b724d409a742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[4]/following::div[1]</value>
      <webElementGuid>d2c9705e-960e-4caa-8cbc-64e29b91050a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select credit card:'])[1]/preceding::div[1]</value>
      <webElementGuid>b3066de6-82b1-412d-a3f5-6d4e9d90b717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div</value>
      <webElementGuid>7ac0606c-2be7-4911-addb-ff32e4e36330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '5Payment information' or . = '5Payment information')]</value>
      <webElementGuid>c988fcd4-d378-4614-8343-1b8a0b8448ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
