<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cardholder name_CardholderName</name>
   <tag></tag>
   <elementGuidId>2b74e5a7-3ee0-47ec-8d26-8f3acd38b88b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CardholderName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CardholderName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ba209ee-55d4-4c8d-896d-09a1dd6b7ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1fb16d76-22ce-4c47-9a38-20dde1e49c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9005ae6b-c31a-4f77-a34b-73829057b2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9fbfedd4-e85d-4e9a-a29a-3b27936b95ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Enter cardholder name</value>
      <webElementGuid>0a1c05f7-d3dd-4708-a6ce-a848e79fb091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CardholderName</value>
      <webElementGuid>18b23f11-bd0e-4307-ad48-3a7d087c179c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CardholderName</value>
      <webElementGuid>cb5537c9-903f-4c3f-8967-9e001fc48455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardholderName&quot;)</value>
      <webElementGuid>e8873c3f-fc66-4372-8881-bdcc14a054e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CardholderName']</value>
      <webElementGuid>5adf7096-fcd2-424f-ae3e-6aa2e956eccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-payment-info-load']/div/div/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>ae356da8-c0d9-4e2f-a592-cb6e85165c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>b14dc7ae-7870-48c1-87ea-1a8eda85dbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CardholderName' and @name = 'CardholderName']</value>
      <webElementGuid>d87b6a4c-d10f-4eea-b7ed-3673db223bb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
