<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_BillingNewAddress.Email</name>
   <tag></tag>
   <elementGuidId>f09f9c52-6cbf-4800-8545-51fdc0555af7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BillingNewAddress_Email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BillingNewAddress_Email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95324bba-5aee-434a-9c04-3ad76015a6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>2d285576-463c-4ec7-8984-a5012d1f2f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-validation-error</value>
      <webElementGuid>26baa7f2-7319-4537-b91b-41a60b4152ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a5beb1d0-c183-4661-9f12-bcc2aadec19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-email</name>
      <type>Main</type>
      <value>Wrong email</value>
      <webElementGuid>45f6ee85-3ac4-4c09-bf3d-5a7726fa286f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Email is required.</value>
      <webElementGuid>f52ff7db-5e52-4aec-91c2-479fbbaf3f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BillingNewAddress_Email</value>
      <webElementGuid>79680c42-e8b4-43d4-a70e-d001a2a6815b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BillingNewAddress.Email</value>
      <webElementGuid>5628c327-b775-498e-8714-9103fd0ed968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BillingNewAddress_Email&quot;)</value>
      <webElementGuid>beeb67f7-2db5-4aa1-bc25-78d7054a4643</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BillingNewAddress_Email']</value>
      <webElementGuid>8bdab9bb-8595-43ef-9ace-a866515afcbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billing-new-address-form']/div/div/div[3]/input</value>
      <webElementGuid>9ceff6a0-a458-4d75-9021-be73c0969dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>6a24cfc2-778a-4e73-aa53-e23e8fa498a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'BillingNewAddress_Email' and @name = 'BillingNewAddress.Email']</value>
      <webElementGuid>238d1a68-cd12-4e91-9521-c1a7cbddc70f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
