<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Credit Card</name>
   <tag></tag>
   <elementGuidId>923a289f-d33a-4cec-aff8-321512137d35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > div.method-name > div.payment-details > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='payment-method-block']/li[2]/div/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>cca7dbfd-dbe2-4d6a-838b-b25aea1e8624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>paymentmethod_1</value>
      <webElementGuid>1190bd48-5f2b-476c-beab-0f9bb5ce9d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Credit Card</value>
      <webElementGuid>c6fabbad-8beb-4752-878c-b9ca187e6dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-method-block&quot;)/li[2]/div[@class=&quot;method-name&quot;]/div[@class=&quot;payment-details&quot;]/label[1]</value>
      <webElementGuid>06b7aa65-7ea8-44b4-8d80-b7a221eee8e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='payment-method-block']/li[2]/div/div[2]/label</value>
      <webElementGuid>63c26f24-d467-486f-b7bd-d5322166cdd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay by cheque or money order'])[1]/following::label[2]</value>
      <webElementGuid>0f1fc86c-d3f7-4672-9ee2-7b7b2465461c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check / Money Order'])[1]/following::label[2]</value>
      <webElementGuid>2cc8ec73-6349-4937-a812-a5346133ba21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay by credit / debit card'])[1]/preceding::label[1]</value>
      <webElementGuid>f8c23d74-e86b-435b-b07b-bf7cd3621e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='«'])[3]/preceding::label[1]</value>
      <webElementGuid>098d8a10-9164-451a-8d07-77074839791f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Credit Card']/parent::*</value>
      <webElementGuid>11905dd8-da5c-4649-8dd4-8bc6484dfcc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div[2]/label</value>
      <webElementGuid>4d030272-1ec3-46eb-85b0-8f4eadd80112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Credit Card' or . = 'Credit Card')]</value>
      <webElementGuid>1c81af43-d2e2-4a9b-ad30-986fb8727567</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
