<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Email is required</name>
   <tag></tag>
   <elementGuidId>0a8e7487-75bb-4688-afdf-3b947faefeec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='billing-new-address-form']/div/div/div[3]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>018ddb3d-f3c7-44f0-85e0-519ce52e9bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field-validation-error</value>
      <webElementGuid>51bb57dc-071f-46be-af5d-2cc8a026a084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-valmsg-for</name>
      <type>Main</type>
      <value>BillingNewAddress.Email</value>
      <webElementGuid>104c5219-0069-4386-946a-a60dc2dcb1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-valmsg-replace</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fb1230fd-8931-49ff-b036-18e217bd93c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email is required.</value>
      <webElementGuid>07ea079c-f1a6-49ad-8253-7217959393b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing-new-address-form&quot;)/div[@class=&quot;enter-address&quot;]/div[@class=&quot;edit-address&quot;]/div[@class=&quot;inputs&quot;]/span[@class=&quot;field-validation-error&quot;]</value>
      <webElementGuid>eec6ccee-5d6c-473a-beca-843662fc7b58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billing-new-address-form']/div/div/div[3]/span[2]</value>
      <webElementGuid>49cb7063-0358-4eb3-bd72-66a26c208f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[1]</value>
      <webElementGuid>c02635f4-31a6-420a-874f-ddccfa298b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[1]/following::span[2]</value>
      <webElementGuid>36039bb5-6f9b-498a-a7b4-a9c3f9fe0685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company:'])[1]/preceding::span[1]</value>
      <webElementGuid>a85a78f4-199b-4ddb-b37a-78e66a4c3ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country:'])[1]/preceding::span[2]</value>
      <webElementGuid>46eb30d2-d33d-4a8c-9824-3c682d062033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email is required.']/parent::*</value>
      <webElementGuid>92564975-413f-433d-9c3f-5006663d04d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span[2]</value>
      <webElementGuid>c13d56fc-723b-48a3-8e3a-f50bec53f7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Email is required.' or . = 'Email is required.')]</value>
      <webElementGuid>9ace5db3-bf7a-4270-8c5b-49b4bcc9adaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
