<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__product_attribute_3</name>
   <tag></tag>
   <elementGuidId>cb0c40f0-3e66-4f94-96f3-2606bf43a613</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_attribute_3_6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_attribute_3_6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e4b3a0b-669c-437b-bee1-aac922e22b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_attribute_3_6</value>
      <webElementGuid>c34cccfa-c380-4652-aac8-775452df9543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6de23266-02fa-412a-8a74-d8eb99555003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_attribute_3</value>
      <webElementGuid>ce559d66-ed0f-48fe-b6a1-e8918fd4b2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>942e6c26-b479-428b-bfa8-6e482e79c131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_attribute_3_6&quot;)</value>
      <webElementGuid>b3f627c1-f861-4589-b882-0a9f488bd660</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_attribute_3_6']</value>
      <webElementGuid>e9e0caa8-d953-447c-be7f-d3768ea445ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dd[@id='product_attribute_input_3']/ul/li/input</value>
      <webElementGuid>6cbfacaa-be63-4441-9e39-fcf061bc5a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>96bfc5ae-ffd3-47e5-9ace-1f33821ee9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'product_attribute_3_6' and @type = 'radio' and @name = 'product_attribute_3']</value>
      <webElementGuid>54424c49-f890-4a54-a5cf-591c838f3202</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
