<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vista Home 50.00_product_attribute_4</name>
   <tag></tag>
   <elementGuidId>6840b078-183a-4e39-83c7-434d92ef65d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_attribute_4_9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_attribute_4_9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>660960df-c243-4f43-add9-b7a0a483cae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_attribute_4_9</value>
      <webElementGuid>b614e2f5-7897-4e5d-b415-7005dc2da658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5ba1a00f-cfb6-4dff-9072-c1d9ac7d87f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_attribute_4</value>
      <webElementGuid>dfbff1d7-2070-43c1-b649-724e5b249d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>103c56f7-82e8-44d9-82d1-37a94116284f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_attribute_4_9&quot;)</value>
      <webElementGuid>35b85319-95b7-480b-87c1-747a4fe42c92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_attribute_4_9']</value>
      <webElementGuid>0f4edb13-ac70-4776-9542-8d3065b70686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dd[@id='product_attribute_input_4']/ul/li[2]/input</value>
      <webElementGuid>f3f497b8-d352-4fec-b67d-d953ad7353a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd[4]/ul/li[2]/input</value>
      <webElementGuid>0ec15668-9c46-4a1a-a772-a9a4a7ad2de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'product_attribute_4_9' and @type = 'radio' and @name = 'product_attribute_4']</value>
      <webElementGuid>450fb059-fa36-4824-a11e-7f49e72746ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
