<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select2.2 GHz Intel Pentium D_04da08</name>
   <tag></tag>
   <elementGuidId>e1b947a0-ad31-4faa-ad41-1ef9bcea1569</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_attribute_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='product_attribute_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>07113c7c-8789-4ea0-8d1f-f7b93335aa68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attr</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>db801cd3-9366-4bef-95c8-775e12ebba1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_attribute_1</value>
      <webElementGuid>3cf52905-78a1-4ff7-9e2a-3b857a0b6f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_attribute_1</value>
      <webElementGuid>fc4a44b5-1063-4d6c-bb44-c071d00b5937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select2.2 GHz Intel Pentium Dual-Core E22002.5 GHz Intel Pentium Dual-Core E2200 [+$15.00]</value>
      <webElementGuid>ffab6fab-ee61-4346-984d-d1e37f5cdfaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_attribute_1&quot;)</value>
      <webElementGuid>67369a93-2e2b-4a4f-9417-66239d92eab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='product_attribute_1']</value>
      <webElementGuid>23eff6cc-a4ab-4f4a-b0a6-15327867335d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dd[@id='product_attribute_input_1']/select</value>
      <webElementGuid>c4a08add-fba2-453b-8fb8-7ad35575e156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>cfb8e039-6081-4ac4-a3c7-26cbe759a5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processor'])[1]/following::select[1]</value>
      <webElementGuid>7992d706-985d-44fe-af76-fe14043d910d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RAM'])[1]/preceding::select[1]</value>
      <webElementGuid>f8baad55-27e7-4c19-9a82-7d27f96d9662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>32190b97-3924-47a5-b7b3-08d1c2a95588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd/select</value>
      <webElementGuid>eeb8ddbd-e449-490d-a9d5-b8659d2989e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'product_attribute_1' and @id = 'product_attribute_1' and (text() = 'Please select2.2 GHz Intel Pentium Dual-Core E22002.5 GHz Intel Pentium Dual-Core E2200 [+$15.00]' or . = 'Please select2.2 GHz Intel Pentium Dual-Core E22002.5 GHz Intel Pentium Dual-Core E2200 [+$15.00]')]</value>
      <webElementGuid>4be7c5d0-97c3-45d5-ac02-f6b7c52f4ff9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
