<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Street address is required</name>
   <tag></tag>
   <elementGuidId>53a1e224-ef30-45f4-b81e-ba3521d8a178</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='billing-new-address-form']/div/div/div[8]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0415a8cf-64aa-423c-b546-bdf18ec32763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field-validation-error</value>
      <webElementGuid>3bf09612-e03c-4255-8d04-f965cbf0635d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-valmsg-for</name>
      <type>Main</type>
      <value>BillingNewAddress.Address1</value>
      <webElementGuid>82882e0e-994e-4079-8a2f-8e8113343d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-valmsg-replace</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>52c9d39b-5759-436a-b544-ccd8d2e28c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Street address is required</value>
      <webElementGuid>e462a2d0-2a64-43cf-b64d-1990a62a453b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing-new-address-form&quot;)/div[@class=&quot;enter-address&quot;]/div[@class=&quot;edit-address&quot;]/div[@class=&quot;inputs&quot;]/span[@class=&quot;field-validation-error&quot;]</value>
      <webElementGuid>ac18cd2a-9fb7-4589-80cf-2c931c069146</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billing-new-address-form']/div/div/div[8]/span[2]</value>
      <webElementGuid>62a1f595-145e-44f1-b1d8-c7d3a8236564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::span[1]</value>
      <webElementGuid>cd2e7367-0604-49aa-8171-b005961dc216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address 1:'])[1]/following::span[2]</value>
      <webElementGuid>8e46cc37-9753-4571-831f-3764e3a677e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address 2:'])[1]/preceding::span[1]</value>
      <webElementGuid>398d8a43-ac70-48f7-bc07-0b3ff00d4b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip / postal code:'])[1]/preceding::span[2]</value>
      <webElementGuid>047f2831-4632-4b51-aeb5-8c6fdffb12be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Street address is required']/parent::*</value>
      <webElementGuid>b1827f5e-861e-45fc-9721-fc946477ac3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/span[2]</value>
      <webElementGuid>1288ab52-6831-40f1-b4cc-ae130dbc3c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Street address is required' or . = 'Street address is required')]</value>
      <webElementGuid>27140e8e-9c96-4bcf-84b9-a89ae83c8f83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
