<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Recipient, , s Name)_giftcard__3edfaa</name>
   <tag></tag>
   <elementGuidId>d9b2eb0d-1dc3-4acd-88c5-a20a3e194933</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#giftcard_43_RecipientName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='giftcard_43_RecipientName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5a4b4c2-c2c2-4b74-a006-dc1cc7c61a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>recipient-name</value>
      <webElementGuid>f6df1c72-9a95-4a74-9c73-15d7ac23a5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d3519491-c30c-4b19-ac8a-17efc9853159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>giftcard_43_RecipientName</value>
      <webElementGuid>3185b0d9-b198-458e-acfc-a10adbc292ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>giftcard_43.RecipientName</value>
      <webElementGuid>1d9d09c2-6862-4b1c-9ed9-6903258e9356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;giftcard_43_RecipientName&quot;)</value>
      <webElementGuid>e716af0d-7afc-4648-a3bc-838c9a1d5c37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='giftcard_43_RecipientName']</value>
      <webElementGuid>7f43e1dd-7061-43e0-aca6-810a9be6aeb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div[2]/div/div[2]/div[5]/div/input</value>
      <webElementGuid>9558e238-f448-457b-9ecd-eb42abe53440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>4dd10cea-3f36-4d23-baa9-4fe7ef7ffcb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'giftcard_43_RecipientName' and @name = 'giftcard_43.RecipientName']</value>
      <webElementGuid>2fabe32f-d807-4feb-b3c2-ceaac19bd4df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
