<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your Name_giftcard_43.SenderName</name>
   <tag></tag>
   <elementGuidId>c7809a2d-6eb4-4084-9303-857ab342509f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#giftcard_43_SenderName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='giftcard_43_SenderName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51049395-0acc-4d83-9372-444594c57406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sender-name</value>
      <webElementGuid>1136e1eb-8bc8-437b-ad16-932351c68c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b978efd8-adad-4aa5-bc20-b1d3b6c609dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>giftcard_43_SenderName</value>
      <webElementGuid>782f9c8b-bab5-4759-a4c0-748c25524048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>giftcard_43.SenderName</value>
      <webElementGuid>71e295bf-2ef3-4c5d-849e-8ea123be384b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;giftcard_43_SenderName&quot;)</value>
      <webElementGuid>c8334510-8f32-4175-b20e-5826664f2065</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='giftcard_43_SenderName']</value>
      <webElementGuid>70ec6e7d-592b-4d2b-9481-d95e8a7105b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div[2]/div/div[2]/div[5]/div[3]/input</value>
      <webElementGuid>e44e8893-36dc-451e-86f8-3bdc5b999edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>c4613cf4-1c54-4f6e-820c-f977ba2045e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'giftcard_43_SenderName' and @name = 'giftcard_43.SenderName']</value>
      <webElementGuid>6f1144c6-67b9-4342-8473-be3cbeb05371</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
