<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qty_addtocart_18.EnteredQuantity</name>
   <tag></tag>
   <elementGuidId>8fb3a2fc-0ef5-43d3-b5fd-cc586055e408</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_enteredQuantity_18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_enteredQuantity_18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1897daa-53bc-4bae-af27-e76ba4b6e595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_enteredQuantity_18</value>
      <webElementGuid>dc8d1808-1525-40d7-9e5e-d4561cda9b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qty-input</value>
      <webElementGuid>ed49c866-9a67-47e7-a2c8-eb7738641d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d5d97cf3-ed01-4af4-b7ed-b49ee2a7f3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter a quantity</value>
      <webElementGuid>1a2cb7ee-016d-4e2b-8676-30f0e6b239ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>690919f0-b7c5-4b69-adcf-db6af849ca23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Qty field is required.</value>
      <webElementGuid>21e7f389-fb17-4f09-b8aa-ff341c61d4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addtocart_18.EnteredQuantity</value>
      <webElementGuid>828b927d-ea57-45fc-93b6-ddb594d8530b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>42a47c36-f003-46f3-b0d3-5a3b7e948e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_enteredQuantity_18&quot;)</value>
      <webElementGuid>cd28f72f-ab0c-4f7b-bd95-16c0d623bdf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_enteredQuantity_18']</value>
      <webElementGuid>e6b2b854-0bbb-4dd4-bd7a-bda1113e90e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div[2]/div/div[2]/div[6]/div/input</value>
      <webElementGuid>89be3a39-7627-4398-a6e9-b685260453f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>1f998105-e55a-4ef3-b3c1-bc16938c260d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'product_enteredQuantity_18' and @type = 'text' and @name = 'addtocart_18.EnteredQuantity']</value>
      <webElementGuid>e1d0bc26-e3cc-46cd-93bc-d00c3c70feb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
