<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_shippingoption</name>
   <tag></tag>
   <elementGuidId>561a9829-08b2-447d-a38c-54bdac70d8ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shippingoption_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='shippingoption_${index}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4bbd4f7c-3e5d-4e22-b20d-e5689cab3e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shippingoption_1</value>
      <webElementGuid>e02b7a82-5c63-4052-a4fc-6fee72b9b4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3279bc1d-f7a2-406e-aa98-4ec302f6147a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shippingoption</value>
      <webElementGuid>7bcd0fa1-882a-434a-b2aa-f1fc1ea49dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Next Day Air___Shipping.FixedByWeightByTotal</value>
      <webElementGuid>f1a862d4-5305-4fac-80fc-dfdc05928863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shippingoption_1&quot;)</value>
      <webElementGuid>c7813a71-e03d-4a73-982f-31c93362aa7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='shippingoption_1']</value>
      <webElementGuid>708ed09a-143f-4875-a3f4-2db4cd34fd9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shipping-methods-form']/ul/li[2]/div/input</value>
      <webElementGuid>30ee3898-b6fb-430a-88f6-d02cbfcd9fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/input</value>
      <webElementGuid>4b41bdcd-54e6-407a-9e58-becf35d9f9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'shippingoption_1' and @type = 'radio' and @name = 'shippingoption']</value>
      <webElementGuid>70688464-ba21-4a4b-9d86-196b4ee2eca9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
